language: common-lisp

# Wookie handler fails with memory corruption when using Travis CI's new container-based architecture.
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:~/nginx/sbin:$PATH
    - LD_LIBRARY_PATH=$HOME/libuv/lib:$LD_LIBRARY_PATH
    - C_INCLUDE_PATH=$HOME/libuv/include:$C_INCLUDE_PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_REQUIRE_SUDO=0
    - COVERAGE_EXCLUDE=t:v1-compat
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl

addons:
  apt:
    packages:
      - libfcgi-dev

before_install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/fukamachi/roswell/require-sudo/scripts/install-for-ci.sh | sh
  # libuv for Wookie
  - curl -L https://github.com/libuv/libuv/archive/v1.6.1.tar.gz | tar xzf -
  - (cd libuv-1.6.1 && ./autogen.sh && ./configure --prefix=$HOME/libuv && make && make install)
  # nginx
  - curl -L http://nginx.org/download/nginx-1.8.0.tar.gz | tar xzf -
  - (cd nginx-1.8.0 && ./configure --prefix=$HOME/nginx && make && make install)

install:
  - ros install prove

before_script:
  - nginx -c "$TRAVIS_BUILD_DIR/t/nginx.conf" -p "$HOME/nginx"
  - ros run -- --version

script:
  - if [ "$LISP" = "sbcl" ]; then
      test_files=$(ls t-*.asd);
    else
      test_files=$(ls t-*.asd | grep -v t-clack-handler-wookie.asd | grep -v t-clack-handler-fcgi.asd);
    fi
  - run-prove $test_files