language: common-lisp

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl

before_install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  # libuv for Wookie
  - curl -L https://github.com/libuv/libuv/archive/v1.2.0.tar.gz | tar xzf -
  - (cd libuv-1.2.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install)
  # nginx for FastCGI handler
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq nginx libfcgi-dev

install:
  - ros install prove

before_script:
  - sudo nginx -c t/nginx.conf -p "$PWD/"
  - ros run -- --version

script:
  - COVERAGE_EXCLUDE=t:v1-compat run-prove t-*.asd
